version: '3'

services:
  nodeapp1:
    image: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodeapp1
    hostname: nodeapp1

  nodeapp2:
    image: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodeapp2
    hostname: nodeapp2

  nodeapp3:
    image: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodeapp3
    hostname: nodeapp3

  nginx1:
    image: nginx
    container_name: nginx1
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  nginx2:
    image: nginx
    container_name: nginx2
    ports:
      - 81:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
